### ISSUE TITLE
How to produce colored point cloud data correctly for ColorPCR?

### ISSUE THREAD

**Issue by ccjccjccj** [mujc2021/ColorPCR#2]
Thanks for your excellent work!

I'm confused about the process of dataset Color3DMatch. I'm trying to test ColorPCR on other dataset (actually, it's a subset of original 3DMatch dataset, including images and the corresponding depth images). To get point cloud with [x, y, z, r, g, b], I directly use the RGB value of each pixel in the image and the corresponding depth value in the depth image to produce point clouds with colors. The resultant point cloud datas are as follow:

[[ 0.36930993  0.3293534   0.8061579   0.22765738  0.19029927  0.19071208]
 [ 0.24407136  0.3538017   0.866       0.6102941   0.53137255  0.44264707]
 [ 0.1376718   0.3538017   0.866       0.2997199   0.21176471  0.232493  ]
 ...
 [-0.67973846  0.1021829   2.599       0.37254903  0.39607844  0.42941177]
 [-0.6804923   0.10296923  2.619       0.38039216  0.4019608   0.41960785]
 [-0.63124615  0.10296923  2.619       0.39294118  0.42509803  0.4062745 ]]

The saved point cloud datas are looked like this:
<img width="460" alt="image" src="https://github.com/user-attachments/assets/8c91d0fb-6c1e-4967-bcec-a0672ba01c39">

However, when I follow the code to produce data_dict with points, hsv values and feats, and input the data_dict into ColorPCR after "registration_collate_fn_stack_mode", I got worse registation performance than original GeoTransformer, and the mean inlier ratio of the output correspondences are about 6% lower than original GeoTransformer (73.6% for ColorPCR and 79.4% for GeoTransformer).

I'm not sure whether I'have correctly produced colored point cloud data using the image-depth pair of the 3DMatch dataset. If possibile, could you please provide the details or relevant code of the production of Color3DMatch dataset? Thanks a lot!

**Comment by mujc2021** [comment]
> Thanks for your excellent work!
> 
> I'm confused about the process of dataset Color3DMatch. I'm trying to test ColorPCR on other dataset (actually, it's a subset of original 3DMatch dataset, including images and the corresponding depth images). To get point cloud with [x, y, z, r, g, b], I directly use the RGB value of each pixel in the image and the corresponding depth value in the depth image to produce point clouds with colors. The resultant point cloud datas are as follow:
> 
> [[ 0.36930993 0.3293534 0.8061579 0.22765738 0.19029927 0.19071208] [ 0.24407136 0.3538017 0.866 0.6102941 0.53137255 0.44264707] [ 0.1376718 0.3538017 0.866 0.2997199 0.21176471 0.232493 ] ... [-0.67973846 0.1021829 2.599 0.37254903 0.39607844 0.42941177] [-0.6804923 0.10296923 2.619 0.38039216 0.4019608 0.41960785] [-0.63124615 0.10296923 2.619 0.39294118 0.42509803 0.4062745 ]]
> 
> The saved point cloud datas are looked like this: <img alt="image" width="460" src="https://private-user-images.githubusercontent.com/50241040/363403611-8c91d0fb-6c1e-4967-bcec-a0672ba01c39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjMwNzMsIm5iZiI6MTcyNTE2Mjc3MywicGF0aCI6Ii81MDI0MTA0MC8zNjM0MDM2MTEtOGM5MWQwZmItNmMxZS00OTY3LWJjZWMtYTA2NzJiYTAxYzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDAzNTI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MjllNWYyYmE3YTljNDFmMzhhNGU4MzAzNTkwOTYwMzVmYjI3MDJiYTgwYjdkYWQ2YjE4NDM0NWZkYTcxN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3trAdLCodLzOUvdMVrbpnYGrsVQjwri0nEY39YAN26Y">
> 
> However, when I follow the code to produce data_dict with points, hsv values and feats, and input the data_dict into ColorPCR after "registration_collate_fn_stack_mode", I got worse registation performance than original GeoTransformer, and the mean inlier ratio of the output correspondences are about 6% lower than original GeoTransformer (73.6% for ColorPCR and 79.4% for GeoTransformer).
> 
> I'm not sure whether I'have correctly produced colored point cloud data using the image-depth pair of the 3DMatch dataset. If possibile, could you please provide the details or relevant code of the production of Color3DMatch dataset? Thanks a lot!

Your method of generating point cloud data is reasonable. A lower inlier ratio is possible since the use of color might introduce incorrect correspondences, although it does provide better features. What are the test results for the registration recall?
For details on how to generate Color3DMatch, you can refer to the supplementary materials of the related paper. The point clouds in Color3DMatch are identical to those preprocessed by Predator, with the only difference being the inclusion of color information.

**Comment by ccjccjccj** [comment]
> > Thanks for your excellent work!
> > I'm confused about the process of dataset Color3DMatch. I'm trying to test ColorPCR on other dataset (actually, it's a subset of original 3DMatch dataset, including images and the corresponding depth images). To get point cloud with [x, y, z, r, g, b], I directly use the RGB value of each pixel in the image and the corresponding depth value in the depth image to produce point clouds with colors. The resultant point cloud datas are as follow:
> > [[ 0.36930993 0.3293534 0.8061579 0.22765738 0.19029927 0.19071208] [ 0.24407136 0.3538017 0.866 0.6102941 0.53137255 0.44264707] [ 0.1376718 0.3538017 0.866 0.2997199 0.21176471 0.232493 ] ... [-0.67973846 0.1021829 2.599 0.37254903 0.39607844 0.42941177] [-0.6804923 0.10296923 2.619 0.38039216 0.4019608 0.41960785] [-0.63124615 0.10296923 2.619 0.39294118 0.42509803 0.4062745 ]]
> > The saved point cloud datas are looked like this: <img alt="image" width="460" src="https://private-user-images.githubusercontent.com/50241040/363403611-8c91d0fb-6c1e-4967-bcec-a0672ba01c39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjMwNzMsIm5iZiI6MTcyNTE2Mjc3MywicGF0aCI6Ii81MDI0MTA0MC8zNjM0MDM2MTEtOGM5MWQwZmItNmMxZS00OTY3LWJjZWMtYTA2NzJiYTAxYzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDAzNTI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MjllNWYyYmE3YTljNDFmMzhhNGU4MzAzNTkwOTYwMzVmYjI3MDJiYTgwYjdkYWQ2YjE4NDM0NWZkYTcxN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3trAdLCodLzOUvdMVrbpnYGrsVQjwri0nEY39YAN26Y">
> > However, when I follow the code to produce data_dict with points, hsv values and feats, and input the data_dict into ColorPCR after "registration_collate_fn_stack_mode", I got worse registation performance than original GeoTransformer, and the mean inlier ratio of the output correspondences are about 6% lower than original GeoTransformer (73.6% for ColorPCR and 79.4% for GeoTransformer).
> > I'm not sure whether I'have correctly produced colored point cloud data using the image-depth pair of the 3DMatch dataset. If possibile, could you please provide the details or relevant code of the production of Color3DMatch dataset? Thanks a lot!
> 
> Your method of generating point cloud data is reasonable. A lower inlier ratio is possible since the use of color might introduce incorrect correspondences, although it does provide better features. What are the test results for the registration recall? For details on how to generate Color3DMatch, you can refer to the supplementary materials of the related paper. The point clouds in Color3DMatch are identical to those preprocessed by Predator, with the only difference being the inclusion of color information.

Thanks for you reply!

The results also showed lower registration recall than GeoTransformer, by evaluating the output LGR result "estimated_transform" using the pretrained models. The benchmark I used is also based on original 3DMatch dataset, it used same test scene spilts with Predator , but aligning image-depth pairs rather than aligning merged point cloud fragments.

Thanks for your illustration in supplementary material, I got the production of Color3DMatch dataset. Although there are still doubts of the frame merging since Predator haven't provided the preprocess code, it seems the performance degradation might not be caused by data preprocess. Is there any color process excuding rgb2hsv before model forward? I currently scale the original rgb values to 1/255 and produce [x, y, z, r, g, b] as shown above, then tranfer the 0-1 rgb values to hsv and directly input into the model as "ref_hsv" or "src_hsv".

**Comment by mujc21** [comment]
This is quite puzzling. Your data preprocessing and color processing should be fine, but I noticed that the point cloud you visualized contains a lot of noise and color errors. Could there be an issue with the code implementation for generating the point cloud? Have you tested ColorPCR on Color3DMatch, and if so, do the results align with the ones we provided?

**Comment by mujc2021** [comment]
This is quite puzzling. Your data preprocessing and color processing should be fine, but I noticed that the point cloud you visualized contains a lot of noise and color errors. Could there be an issue with the code implementation for generating the point cloud? Have you tested ColorPCR on Color3DMatch, and if so, do the results align with the ones we provided?

**Comment by ccjccjccj** [comment]
> This is quite puzzling. Your data preprocessing and color processing should be fine, but I noticed that the point cloud you visualized contains a lot of noise and color errors. Could there be an issue with the code implementation for generating the point cloud? Have you tested ColorPCR on Color3DMatch, and if so, do the results align with the ones we provided?

Yes, the reproduced result on Color3DMatch with the pretrained model is aligned with the paper, and both inlier ratio and recall are higher than GeoTransformer. I founded the performance degradation is happened only after changing the [x, y, z, r, g, b] data from loaded Color3DMatch's npy to my produced image-depth data. The customized reading part is as follow (has been integrated into one function for better display):

    def load_3DMatch(self, image_file, depth_file, intrinsics_file):
        image = cv2.imread(image_file)
        depth = o3d.io.read_image(depth_file)
        intrinsics = np.loadtxt(intrinsics_file, dtype = np.float32)
    
        # Generate RGB point clouds
        camera_intrinsic = o3d.camera.PinholeCameraIntrinsic()
        camera_intrinsic.set_intrinsics(width = img.shape[0], height = img.shape[1], fx = intrinsics[0,0], fy = intrinsics[1,1], cx = intrinsics[0,2], cy = intrinsics[1,2])
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = o3d.geometry.Image(img)
        rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(img, dep, depth_scale = 1000, depth_trunc = 65.535, convert_rgb_to_intensity = False)
        pc = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image, camera_intrinsic)
    
        # Downsample point clouds
        pc = pc.voxel_down_sample(self.cfg.voxel_size)
        points = np.asarray(pc.points)
        color = np.asarray(pc.colors)
        pc = np.concatenate([points, color], axis = 1).astype(np.float32)
    
        return pc

The voxel_size is set to 0.025. The first three channels are used to produce points. A color.rgb2hsv is then applied for the last three channels to get hsv. The input initial feats are np.ones that is same with original code.

**Comment by mujc2021** [comment]
The code seems fine, but the visualization clearly shows many errors. You might need to debug by focusing on the visualization. If the visualization looks correct, the results should follow. Using a point cloud with much color noise will inevitably introduce many errors, and the registration results may not be good.

**Comment by ccjccjccj** [comment]
Thanks for your patient response! I think the noise and color error are brought by the original data, since they mostly occured on locations that have a large neighboring depth variation, which can be caused by calibration error. I guess Predator's merging process with TSDF can somehow relieve the noise of each frame, and reconstruct colored point clouds using all frames instead of only one frame might provide more accurate color information for each point. It seems that the datas of this benchmark may not be suitable for ColorPCR...

**Comment by mujc2021** [comment]
We recommend that you try debugging. In our experiments, we tested the registration of RGBD point clouds and achieved results far better than purely geometric methods. Moreover, our visualized RGBD point clouds did not contain as many color and geometry errors. In the future, we might open-source this part of the data processing code later. However, if you're in a hurry, we suggest debugging on your own firstly.

**Comment by ccjccjccj** [comment]
Thanks! I will make a careful check.
