### ISSUE TITLE
如何运行代码？

### ISSUE THREAD

**Issue by xl232lx** [mujc2021/ColorPCR#4]
作者您好，请问一下，如何使用自己的pcd点云文件，输入参数运行代码进行配准，得出变换矩阵或可视化的结果？

**Comment by mujc2021** [comment]
您好，如果是多个pcd文件的话，可以尝试组织为我们提供的数据集格式，直接运行测试代码来得到npz文件，这个文件中的key="estimated_transform"存储了变换矩阵（4*4）。如果是单个文件的话，您可以参考geotransformer/datasets/registration/threedmatch/dataset.py中的点云加载代码来进行对应修改来加载您的pcd。输出的变换矩阵可以参考model.py的estimated_transform变量。

**Comment by xl232lx** [comment]
> 您好，如果是多个pcd文件的话，可以尝试组织为我们提供的数据集格式，直接运行测试代码来得到npz文件，这个文件中的key="estimated_transform"存储了变换矩阵（4*4）。如果是单个文件的话，您可以参考geotransformer/datasets/registration/threedmatch/dataset.py中的点云加载代码来进行对应修改来加载您的pcd。输出的变换矩阵可以参考model.py的estimated_transform变量。

您好，感谢您的解答，我想再请问一下，我这边测试一组数据，数据中只有源点云和目标点云两个pcd文件，也是直接运行测试代码不？

**Comment by ymclsh** [comment]
> 您好，如果是多个pcd文件的话，可以尝试组织为我们提供的数据集格式，直接运行测试代码来得到npz文件，这个文件中的key="estimated_transform"存储了变换矩阵（4*4）。如果是单个文件的话，您可以参考geotransformer/datasets/registration/threedmatch/dataset.py中的点云加载代码来进行对应修改来加载您的pcd。输出的变换矩阵可以参考model.py的estimated_transform变量。

Hi, I am trying to convert my won point cloud data according to the dataset provided. One question is if just for testing,  do I need to generate metadata, the .pkl file in your dataset and how? My own point clouds are generated by scanning, btw.  
Thanks for your time and help in advance.

**Comment by mujc2021** [comment]
> Hi, I am trying to convert my won point cloud data according to the dataset provided. One question is if just for testing, do I need to generate metadata, the .pkl file in your dataset and how? My own point clouds are generated by scanning, btw. Thanks for your time and help in advance.
I think you can generate an easy .pkl file to test your own point clouds. You can use pickel to load our .pkl and generate a similar one for your data. Some keys are not important for testing (like "overlap ratio") so you can set them to None.

**Comment by mujc2021** [comment]
> > 您好，如果是多个pcd文件的话，可以尝试组织为我们提供的数据集格式，直接运行测试代码来得到npz文件，这个文件中的key="estimated_transform"存储了变换矩阵（4*4）。如果是单个文件的话，您可以参考geotransformer/datasets/registration/threedmatch/dataset.py中的点云加载代码来进行对应修改来加载您的pcd。输出的变换矩阵可以参考model.py的estimated_transform变量。
> 
> Hi, I am trying to convert my won point cloud data according to the dataset provided. One question is if just for testing, do I need to generate metadata, the .pkl file in your dataset and how? My own point clouds are generated by scanning, btw. Thanks for your time and help in advance.

I think you can generate an easy .pkl file to test your own point clouds. You can use pickel to load our .pkl and generate a similar one for your data. Some keys are not important for testing (like "overlap ratio") so you can set them to None.

**Comment by ymclsh** [comment]
Thanks for the explanation. With your help, npz files  are generated successfully. 
However, the result seems not good enough and I do think I might make some mistakes during the visualization process. 
In each npz file, I take "ref_points", "src_points" and "estimated_transform", I transferred src_points by doing : estimated_transform @ src_points_h.T, and visualized ref_points and transformed src_points for several npz. The screen is attached.   
Do you know where I am wrong? Thanks!

![Screenshot from 2025-01-07 10-53-18](https://github.com/user-attachments/assets/12514824-9235-4ad4-ab42-4281aa709606)

**Comment by mujc2021** [comment]
> Thanks for the explanation. With your help, npz files are generated successfully. However, the result seems not good enough and I do think I might make some mistakes during the visualization process. In each npz file, I take "ref_points", "src_points" and "estimated_transform", I transferred src_points by doing : estimated_transform @ src_points_h.T, and visualized ref_points and transformed src_points for several npz. The screen is attached. Do you know where I am wrong? Thanks!
> 
> ![Screenshot from 2025-01-07 10-53-18](https://private-user-images.githubusercontent.com/24773085/400617116-12514824-9235-4ad4-ab42-4281aa709606.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyMTkxNzQsIm5iZiI6MTczNjIxODg3NCwicGF0aCI6Ii8yNDc3MzA4NS80MDA2MTcxMTYtMTI1MTQ4MjQtOTIzNS00YWQ0LWFiNDItNDI4MWFhNzA5NjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA3VDAzMDExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NDg1NGU3YjYwOTNkZjllMzYyY2EwY2JmZjY4MTQ1ZjdhMmEzZjk5NjM2OGRiNmI1YTE4MTJjNzAyNThmYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0-wIpYaY8qgrDsXUDL0mqVZXxFKmIjtyNUdGA6aYAVs)

You can try this function:
def apply_transform(points: torch.Tensor, transform: torch.Tensor, normals: Optional[torch.Tensor] = None):
    if normals is not None:
        assert points.shape == normals.shape
    if transform.ndim == 2:
        rotation = transform[:3, :3]
        translation = transform[:3, 3]
        points_shape = points.shape
        points = points.reshape(-1, 3)
        points = torch.matmul(points, rotation.transpose(-1, -2)) + translation
        points = points.reshape(*points_shape)
        if normals is not None:
            normals = normals.reshape(-1, 3)
            normals = torch.matmul(normals, rotation.transpose(-1, -2))
            normals = normals.reshape(*points_shape)
    elif transform.ndim == 3 and points.ndim == 3:
        rotation = transform[:, :3, :3]  # (B, 3, 3)
        translation = transform[:, None, :3, 3]  # (B, 1, 3)
        points = torch.matmul(points, rotation.transpose(-1, -2)) + translation
        if normals is not None:
            normals = torch.matmul(normals, rotation.transpose(-1, -2))
    else:
        raise ValueError(
            'Incompatible shapes between points {} and transform {}.'.format(
                tuple(points.shape), tuple(transform.shape)
            )
        )
    if normals is not None:
        return points, normals
    else:
        return points

Btw, I think you can use different colors for two point clouds for better visualization.

**Comment by mujc2021** [comment]
> Thanks for the explanation. With your help, npz files are generated successfully. However, the result seems not good enough and I do think I might make some mistakes during the visualization process. In each npz file, I take "ref_points", "src_points" and "estimated_transform", I transferred src_points by doing : estimated_transform @ src_points_h.T, and visualized ref_points and transformed src_points for several npz. The screen is attached. Do you know where I am wrong? Thanks!
> 
> ![Screenshot from 2025-01-07 10-53-18](https://private-user-images.githubusercontent.com/24773085/400617116-12514824-9235-4ad4-ab42-4281aa709606.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyMTkxNzQsIm5iZiI6MTczNjIxODg3NCwicGF0aCI6Ii8yNDc3MzA4NS80MDA2MTcxMTYtMTI1MTQ4MjQtOTIzNS00YWQ0LWFiNDItNDI4MWFhNzA5NjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA3VDAzMDExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NDg1NGU3YjYwOTNkZjllMzYyY2EwY2JmZjY4MTQ1ZjdhMmEzZjk5NjM2OGRiNmI1YTE4MTJjNzAyNThmYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0-wIpYaY8qgrDsXUDL0mqVZXxFKmIjtyNUdGA6aYAVs)

You can try this function:
```
def apply_transform(points: torch.Tensor, transform: torch.Tensor, normals: Optional[torch.Tensor] = None):
    if normals is not None:
        assert points.shape == normals.shape
    if transform.ndim == 2:
        rotation = transform[:3, :3]
        translation = transform[:3, 3]
        points_shape = points.shape
        points = points.reshape(-1, 3)
        points = torch.matmul(points, rotation.transpose(-1, -2)) + translation
        points = points.reshape(*points_shape)
        if normals is not None:
            normals = normals.reshape(-1, 3)
            normals = torch.matmul(normals, rotation.transpose(-1, -2))
            normals = normals.reshape(*points_shape)
    elif transform.ndim == 3 and points.ndim == 3:
        rotation = transform[:, :3, :3]  # (B, 3, 3)
        translation = transform[:, None, :3, 3]  # (B, 1, 3)
        points = torch.matmul(points, rotation.transpose(-1, -2)) + translation
        if normals is not None:
            normals = torch.matmul(normals, rotation.transpose(-1, -2))
    else:
        raise ValueError(
            'Incompatible shapes between points {} and transform {}.'.format(
                tuple(points.shape), tuple(transform.shape)
            )
        )
    if normals is not None:
        return points, normals
    else:
        return points
```
Btw, I think you can use different colors for two point clouds for better visualization.
