### ISSUE TITLE
关于显存问题

### ISSUE THREAD

**Issue by xl232lx** [mujc2021/ColorPCR#5]
作者您好，再次请教一下以下两个问题：
问题一
       我运行自己数据集，部分数据会出现RuntimeError: CUDA out of memory. Tried to allocate 6.26 GiB (GPU 0; 11.76 GiB total capacity; 6.60 GiB already allocated; 3.96 GiB free; 7.05 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF这个报错，请问一下， 这个是什么原因，是跟点云的点数有关系么？能请教一下怎么解决么？
问题二
       我点云文件只有xyz信息，我这边随机添加了rgb信息，有些数据也是可以正常配准的，这是正常现象不？

**Comment by mujc2021** [comment]
您好，关于问题一，应该是点云的点数太大了，您可以在dataloader中限制点云的点数，建议通过限制超点个数来防止爆显存，因为transformer结构是应用于超点的。
问题二，是正常的，只要shape匹配都是可以运行算法的，能正常匹配说明几何信息已经足够实现正确的配准

**Comment by xl232lx** [comment]
> 您好，关于问题一，应该是点云的点数太大了，您可以在dataloader中限制点云的点数，建议通过限制超点个数来防止爆显存，因为transformer结构是应用于超点的。 问题二，是正常的，只要shape匹配都是可以运行算法的，能正常匹配说明几何信息已经足够实现正确的配准

非常感谢您的回复！非常优秀的工作！
